### ISSUE TITLE
Search Bar Not Showing

### ISSUE THREAD

**Issue by PasinduPiumal1** [TryGhost/Dawn#50]
I install Ghost on my computer. I installed Dawn Theme But the search bar Not showing.  I added gh_search_key in code injection but the search bar is not showing!!
![Screenshot (152)](https://user-images.githubusercontent.com/70275854/144700736-9dfb78dd-113b-49f0-97b0-11de6e67ffdf.png)

**Comment by minimaluminium** [comment]
Hey @PasinduPiumal1,

The API key for search function now uses the custom theme setting in `Settings > Design > Site-wide` instead of code injection method which was used previously. Sorry about the lack of docs, it'll soon be updated! 

<img width="359" alt="CleanShot 2021-11-30 at 12 52 13@2x" src="https://user-images.githubusercontent.com/1418797/144789689-06afa12d-196a-4c99-90ee-9665b912cf18.png">
