### ISSUE TITLE
Questions around the re-rooting of the main branch

### ISSUE THREAD

**Issue by SingingTree** [TryGhost/Dawn#67]
https://github.com/TryGhost/Dawn/commit/505e21f9a2ea460a67d77a5c5d0b5771b498db0a appears to have re-rooted the main branch and looks to be based on breaking out the changes from the Themes mono repo in https://github.com/TryGhost/Themes/pull/98 back into the specific repos for each theme.

Was there a reason for rerooting main, rather than building on top of the existing branch?

Should contributions for the theme going forward be made against this repo, or against the Dawn theme in the mono repo over at https://github.com/TryGhost/Themes ?

**Comment by minimaluminium** [comment]
Hey @SingingTree,

The separate theme repos are now synced automatically with the monorepo [TryGhost/Themes](https://github.com/TryGhost/Themes). The action setup for this automation uses force push, so the theme repos needed to start from fresh.

If you're looking to contribute rather than modifying a theme for your use, [TryGhost/Themes](https://github.com/TryGhost/Themes) should be the one you need.
