### ISSUE TITLE
Why are you using the favicon as logo?

### ISSUE THREAD

**Issue by benjaminach** [TryGhost/Dawn#7]
Hello,

Thanks for this great theme!

Why are you using site.icon as the logo/main image for this theme?

I dont think that's appropriate as this icon is also used as a favicon.
Why not use the site.logo or site.cover image instead?

Thanks

**Comment by minimaluminium** [comment]
Hey Benjamin! The publication icon (`@site.icon`) was used, because this is a square image used in the UI of your publication.

The publication logo (`@site.logo`) is used as a logo image which replaces the text logo when chosen.

For the publication cover (`@site.cover_image`), it's usually an large background for your publication, but if you want to use this instead of the icon, replace `@site.icon` with `@site.cover_image` on [this line](https://github.com/TryGhost/Dawn/blob/master/partials/cover.hbs#L5).
